<a href="https://colab.research.google.com/github/dannyxia7/UCSD_DSC_207R/blob/main/Danny_Xia_Week3_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 3 Assignment Notebook

# UC San Diego OMDS DSC 207

There is no autograder for this assignment. All portions are manually graded, and you will submit a PDF of your Colab notebook rather than your Python notebook itself. Within this notebook, you must also paste a link to this notebook. Instructions for exporting your Colab notebook as a PDF are at the bottom of this notebook.

## Part 0

Add a shareable link (with public viewing permissions) to this Colab notebook in a **text box** (not code block) below. If you add it in a code block, we may not be able to access it if the link is too long. This is required so that we are able to verify and potentially run your code.

If you used Jupyter Notebooks, upload it to Colab first and share the link below.

LINK TO THIS COLAB NOTEBOOK HERE:

### Import pandas and numpy
Rename libraries as pd and np while importing.

In [ ]:
# LOAD LIBRARIES
import pandas as pd
import numpy as np

## Part 1

### 1.1 **Fetch and read book data**
In this assignment, we will be working with a dataset of books - https://raw.githubusercontent.com/dsc207rfall2023/fa23course-dsc207r/main/assignments/Week%203/input_data/books_hw.csv. As you may have noticed, the file type is csv - comma separated values. **Read this data into a pandas dataframe `books`.** (Hint - It might be useful to look into [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) for reading csv files. If you come across some 'bad' lines in the dataset, the parameter `on_bad_lines` may be useful)) [0.5pt]

In [ ]:
books = pd.read_csv("https://raw.githubusercontent.com/dsc207rfall2023/fa23course-dsc207r/main/assignments/Week%203/input_data/books_hw.csv", on_bad_lines = 'warn')

<ipython-input-26-4b2243614b6c>:1: ParserWarning: Skipping line 3350: expected 12 fields, saw 13
Skipping line 4704: expected 12 fields, saw 13
Skipping line 5879: expected 12 fields, saw 13
Skipping line 8981: expected 12 fields, saw 13

  books = pd.read_csv("https://raw.githubusercontent.com/dsc207rfall2023/fa23course-dsc207r/main/assignments/Week%203/input_data/books_hw.csv", on_bad_lines = 'warn')

In [ ]:
assert isinstance(books, pd.DataFrame)

<!-- BEGIN QUESTION -->

### 1.2 **To verify that `books` contains data, print the first 10 rows of the dataset.**
Verify the same with CSV file. [0.5pt]

In [ ]:
# WRITE YOUR CODE HERE
books.head(10)

,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
bookID,,,,,,,,,,,
1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,2006-09-16,Scholastic Inc.
2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,2004-09-01,Scholastic Inc.
4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,2003-11-01,Scholastic
5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,2004-05-01,Scholastic Inc.
8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,2004-09-13,Scholastic
9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.74,0976540606,9780976540601,en-US,152,19,1,2005-04-26,Nimble Books
10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,0439827604,9780439827607,eng,3342,28242,808,2005-09-12,Scholastic
12,The Ultimate Hitchhiker's Guide: Five Complete...,Douglas Adams,4.38,0517226952,9780517226957,eng,815,3628,254,2005-11-01,Gramercy Books
13,The Ultimate Hitchhiker's Guide to the Galaxy ...,Douglas Adams,4.38,0345453743,9780345453747,eng,815,249558,4080,2002-04-30,Del Rey Books
14,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,4.22,1400052920,9781400052929,eng,215,4930,460,2004-08-03,Crown

In [ ]:
print(books["average_rating"].mean())
print(books['average_rating'].std())
print(books['average_rating'].max())
print(books['average_rating'].min())

3.9340753393868564
0.3504853116512759
5.0
0.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

<!-- END QUESTION -->

### 1.3 **Change Index to bookID**
In the above dataframe, you can see that there is an index before the first column `bookID`. Instead we can have bookID as the index for better searching and filtering. **Change the index of `books` to `bookID`.** (Hint - make sure the you are applying the changes to the same dataframe) [0.5pt]

In [ ]:
# WRITE YOUR CODE HERE
books = books.set_index("bookID")

In [ ]:
assert books.shape == (11123, 11)

<!-- BEGIN QUESTION -->

### 1.4 To verify change in index, **print the first 10 rows of the updated dataframe `books`.** [0.5pt]

In [ ]:
 # WRITE YOUR CODE HERE
books.head(10)

,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
bookID,,,,,,,,,,,
1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic
9,"Unauthorized Harry Potter Book Seven News: ""Ha...",W. Frederick Zimmerman,3.74,0976540606,9780976540601,en-US,152,19,1,4/26/2005,Nimble Books
10,Harry Potter Collection (Harry Potter #1-6),J.K. Rowling,4.73,0439827604,9780439827607,eng,3342,28242,808,9/12/2005,Scholastic
12,The Ultimate Hitchhiker's Guide: Five Complete...,Douglas Adams,4.38,0517226952,9780517226957,eng,815,3628,254,11/1/2005,Gramercy Books
13,The Ultimate Hitchhiker's Guide to the Galaxy ...,Douglas Adams,4.38,0345453743,9780345453747,eng,815,249558,4080,4/30/2002,Del Rey Books
14,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,4.22,1400052920,9781400052929,eng,215,4930,460,8/3/2004,Crown

<!-- END QUESTION -->

### 1.5 **Store the total samples (rows) in dataset in `num_books` and print the result as well.** [0.5pt]

In [ ]:
num_books = books.index.size
print(num_books)

11123

## Part 2

### 2.1 **Filtering dataframes**

We may want the ability to get data based on certain criteria to perform analysis or derive statistics. **Get all rows from the dataframe `books` for which author is "J.R.R. Tolkien" and store it in `booksByTolkien`.** [0.5pt]

In [ ]:
# WRITE YOUR CODE HERE
booksByTolkien = books.loc[books["authors"] == "J.R.R. Tolkien"]
booksByTolkien.head()

,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
bookID,,,,,,,,,,,
30,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,J.R.R. Tolkien,4.59,0345538374,9780345538376,eng,1728,101233,1550,9/25/2012,Ballantine Books
31,The Lord of the Rings (The Lord of the Rings ...,J.R.R. Tolkien,4.50,0618517650,9780618517657,eng,1184,1710,91,10/21/2004,Houghton Mifflin Harcourt
34,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien,4.36,0618346252,9780618346257,eng,398,2128944,13670,9/5/2003,Houghton Mifflin Harcourt
2331,The Lord of the Rings- 3 volumes set (The Lord...,J.R.R. Tolkien,4.50,0618574999,9780618574995,en-US,1438,232,9,6/1/2005,Mariner Books
5898,The Lord of the Rings (The Lord of the Rings ...,J.R.R. Tolkien,4.50,0007136587,9780007136582,eng,1200,682,43,9/16/2002,Not Avail

In [ ]:
assert isinstance(booksByTolkien, pd.DataFrame)

### 2.2 **Data analysis using dataframes**

Since a dataframe is a collection of large amounts of data, often dealing with numeric data. This data can be used to create aggregations, which is very useful in deriving actionable insights.

**Mean - Find average rating of all books present in the dataset and store in `avg_book_rating`.** [0.5pt]

**Calculate the sum of rating_count in `booksByTolkien` and store it in `total_rating_count`** [0.5pt]

In [ ]:
avg_book_rating = books["average_rating"].mean()
print(avg_book_rating)
total_rating_count = booksByTolkien['ratings_count'].sum()
print(total_rating_count)

3.9340753393868564
4776638

### 2.3 **Average rating of books written by "J.K. Rowling"**

Use the ability of filtering dataframes and find the mean of the filtered dataframe. Store the result in `avg_Rowling_book_rating` [1pt]

In [ ]:
avg_Rowling_book_rating = books.loc[books['authors'] == 'J.K. Rowling']['average_rating'].mean()
print(avg_Rowling_book_rating)

4.513636363636365

## Part 3

### 3.1 **How many unique authors are present in this dataset?**
Store the result in `num_authors`. (Hint - is there a function to do this?) [0.5pt]

In [ ]:

num_authors = books['authors'].nunique()
print(num_authors)

6639

### 3.2 **What is the maximum average rating for a book in the dataset?**
Store the result in `maxRating`. Print `maxRating`. [0.5pt]

In [ ]:

maxRating = books['average_rating'].max()
print(maxRating)

5.0

<!-- BEGIN QUESTION -->

### 3.3 **Authors of the books which are rated maximum**
One sample data analysis task would be to find the authors who have high rated books. This information could be of great use to a publisher or book store chain.


Store the author name, book title and average rating of the books who have maximum rating, in a dataframe `maxRatedAuthors`. Print `maxRatedAuthors`. [0.5pt]

Print the number of max rated authors. [0.5pt]

In [ ]:
maxRatedAuthors = books[books['average_rating']  == maxRating].loc[:, ['authors', 'title', 'average_rating']]
print(maxRatedAuthors)

                                                  authors  \
bookID
2034                  Aristophanes/F.W. Hall/W.M. Geldart
2560                      Julie Sylvester/David Sylvester
2843                                       Tara MacCarthy
4287                 Middlesex Borough Heritage Committee
14741                                          Tim Bogenn
17224                                       John  Diamond
17830                                     Elena N. Mahlow
18184                     Ian        Martin/Katie Elliott
19786                                          NOT A BOOK
19788                                          NOT A BOOK
20954                            Dennis Adler/R.L. Wilson
20957                                      R. McL. Wilson
23276                                        Ross Garnaut
23552                                Todd Davis/Marc Frey
25426                     Nicholas    Evans/Rhonda  Evans
32823    Chris    Green/Chris Wright/Paul Douglas Gardner
36492                                  William C. Dowling
36853   Laura Driscoll/Alisa Klayman-Grodsky/Eric     ...
38804                                       Keith Donohue
39580                                   James E. Campbell
39829                                 Sheri Rose Shepherd
41639                                    Sara Barton-Wood

                                                    title  average_rating
bookID
2034    Comoediae 1: Acharenses/Equites/Nubes/Vespae/P...             5.0
2560                    Willem de Kooning: Late Paintings             5.0
2843    Literature Circle Guide: Bridge to Terabithia:...             5.0
4287    Middlesex Borough (Images of America: New Jersey)             5.0
14741   Zone of the Enders: The 2nd Runner Official St...             5.0
17224   The Diamond Color Meditation: Color Pathway to...             5.0
17830   Bulgakov's the Master and Margarita: The Text ...             5.0
18184   The Complete Theory Fun Factory: Music Theory ...             5.0
19786   The Goon Show  Volume 4: My Knees Have Fallen ...             5.0
19788   The Goon Show  Volume 11: He's Fallen in the W...             5.0
20954                                 Winchester Shotguns             5.0
20957   Colossians and Philemon: A Critical and Exeget...             5.0
23276                           Taxation of Mineral Rents             5.0
23552                         The New Big Book of America             5.0
25426   Delwau Duon: Peintiadau Nicholas Evans = Symph...             5.0
32823        Fanning the Flame: Bible  Cross  and Mission             5.0
36492   Oliver Wendell Holmes in Paris: Medicine  Theo...             5.0
36853                  Tyrannosaurus Wrecks (Stanley  #1)             5.0
38804       The Irish Anatomist: A Study of Flann O'Brien             5.0
39580   The American Campaign: U.S. Presidential Campa...             5.0
39829   His Princess Devotional: A Royal Encounter Wit...             5.0
41639          Bill Gates: Computer Legend (Famous Lives)             5.0

In [ ]:
assert maxRatedAuthors is not None and isinstance(maxRatedAuthors, pd.DataFrame)

assert all(col in maxRatedAuthors.columns for col in ['authors', 'title', 'average_rating'])

<!-- END QUESTION -->

### 3.4 List books whose rating count is greater than 2000 and average rating is more than 4.70

Store this into a dataframe `popularBooks`. Ensure that all the columns are preserved. Print `popularBooks`. [0.5pt]

In [ ]:
popularBooks = books[books['ratings_count'] > 2000][books['average_rating'] > 4.7]

<ipython-input-42-225e8a812d22>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  popularBooks = books[books['ratings_count'] > 2000][books['average_rating'] > 4.7]

In [ ]:
assert popularBooks is not None and isinstance(popularBooks, pd.DataFrame)

<!-- BEGIN QUESTION -->

### 3.5 Describe the dataset
We want to use statistics to get a general idea of the dataframe and its numerical values.

Using [describe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html), provide the counts, mean, standard deviation, mins, percentiles and maxs of the dataframe `popularBooks`. [0.5pt]

In [ ]:
# WRITE YOUR CODE HERE
popularBooks.describe()

,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,6.000000,6.000000e+00,6.000000,6.000000,6.000000
mean,4.753333,9.780672e+12,1322.666667,24122.666667,430.000000
std,0.041793,1.850730e+08,1421.230828,13261.232622,351.679968
min,4.710000,9.780440e+12,96.000000,3613.000000,85.000000
25%,4.722500,9.780515e+12,176.000000,17492.500000,195.500000
50%,4.745000,9.780741e+12,816.000000,26058.500000,296.500000
75%,4.775000,9.780812e+12,2381.500000,31220.250000,681.750000
max,4.820000,9.780836e+12,3342.000000,41428.000000,930.000000

<!-- END QUESTION -->

## Part 4

### 4.1 Which are 7 most popular book languages(language_code) in this dataset?
Print the `language_code` and count of the 7 highest occuring languages in the dataset. (Hint - `<dataframe>.<column-name>` gives you a series. With this, can you use [value_counts()](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) to get the answer? Store the result in `popularLang`. [1pt]

In [ ]:
popularLang = books['language_code'].value_counts().head(7)
print(popularLang)

language_code
eng      8908
en-US    1408
spa       218
en-GB     214
fre       144
ger        99
jpn        46
Name: count, dtype: int64

In [ ]:
assert type(popularLang) == pd.Series

assert len(popularLang) == 7

<!-- BEGIN QUESTION -->

### 4.2 Print the number of books that have an average rating within 2 standard deviations from mean average rating of the entire dataset.
[Standard deviation](https://en.wikipedia.org/wiki/Standard_deviation) tells you how spread out the data is. It is a measure of how far each observed value is from the mean. In any distribution, about 95% of values will be within 2 standard deviations of the mean.
Hence, for the given task, we want to find the number of books who have an average rating from `mean-2*std_dev` to `mean+2*std_dev`. [1pt]

In [ ]:
# WRITE YOUR CODE HERE
avg_rating_std = books["average_rating"].std()
avg_rating_mean = books["average_rating"].mean()
n_books_mean_std = books[books['average_rating'].between(avg_rating_mean - 2*avg_rating_std, avg_rating_mean + 2*avg_rating_std)]
n_books_mean_std.index.size

10854

<!-- END QUESTION -->

### 4.3 Find books with language code as 'ger' and whose publication date is between 2001 and 2005. (Optional)
(Hint - How do we get the year from the publication date in its current form? Can we use [pd.to_datetime](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html) to extract what we need for this task?)

In [ ]:
# WRITE YOUR CODE HERE
books['publication_date'] = pd.to_datetime(books['publication_date'], errors = 'coerce')
books_ger_pub_date = books[(books['language_code'] == 'ger') & (books['publication_date'] >= '2001-01-01') & (books['publication_date'] <= '2005-12-31')].sort_values(by=['publication_date'])
books_ger_pub_date.head(10)

,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
bookID,,,,,,,,,,,
25740,Der Golem,Isaac Bashevis Singer,3.75,349175710X,9783491757103,ger,64,2,0,2001-02-01,Patmos
23439,Die Farbe von Wasser,James McBride,4.09,342661278X,9783426612781,ger,317,38,1,2001-02-01,Droemer Knaur
11520,Endymion: Pforten der Zeit,Dan Simmons,4.17,3442353920,9783442353927,ger,672,3,0,2001-02-01,Blanvalet Taschenbuch
29140,Melliandra,J.V. Jones,3.79,3404204077,9783404204076,ger,734,5,0,2001-03-01,Lübbe
18383,Jane Eyre,Charlotte Brontë,4.12,3717519646,9783717519645,ger,784,432,26,2001-03-01,Manesse Verlag
33751,Die Naschkatzen,Jennifer Crusie,3.94,3442448964,9783442448968,ger,480,15,1,2001-04-01,Goldmann Verlag
41911,Harry Potter und der Gefangene von Askaban (Ha...,J.K. Rowling,4.56,355155210X,9783551552105,ger,448,30,2,2001-04-01,Carlsen
22718,Pusteblume,Marian Keyes,3.81,3453189345,9783453189348,ger,560,59,0,2001-05-01,Heyne
14883,Die Wahrheit der letzten Stunde,Jodi Picoult,3.80,3404145844,9783404145843,ger,684,7,2,2001-08-01,Lübbe
30446,Schöne Lügen,Rachel Ryan/Sandra Brown,3.60,3442354994,9783442354993,ger,255,13,1,2001-09-01,Goldmann

## Part 5: Video

Submit a video no longer than 4 minutes with the following components:
* How you read the books dataset CSV, including how you skipped "bad" lines. (1 min) [1 pt]
* Describe the dataset. For instance, you could explain what some of the columns are, how many books are in the dataset, some statistical information about mean and standard deviation, etc. (1 min) [1 pt]
* Pick one or two subproblems from the assignment and describe the code in fine detail. Ensure you are sharing your screen with your code for this portion. (2 min) [2 pt] You might explain:
    * How you found the average rating of books written by "J.K. Rowling" or how you listed all books whose rating count is greater than 2000 and average rating is more than 4.70.
    * How you listed all books whose rating count is greater than 2000 and average rating is more than 4.70.

Additionally (and this is important), ensure you follow the format the video submission. If one of these criteria is missing, we will not grade the video.
* Show your ID at the start of the video so we know who you are.
* Show your code in the video by screensharing.
* Show your face in the video.

Upload the recorded video to your Drive and paste the shareable (publicly viewable) link in a **text box** below.

Note: Ensure that we are able to view the video.

LINK TO YOUR VIDEO HERE: https://drive.google.com/file/d/197poamjiS6dP24RokgvwGC7duTz52Omj/view?usp=sharing

## Part 6: Extra credit (optional)

Below, we have provided code to download a CSV file containing Pokemon data.

First, identify two interesting questions that you want to answer about the dataset. These questions should not be easily answerable by a simple visual inspection of the dataset. The questions should have quantitative answers.

Then, find the answer to your two interesting questions using pandas dataframes and dataframe operations.

Rubric:
* Read the CSV file into a pandas dataframe. (0.5 pt)
* Perform pandas dataframe operations to answer your chosen question #1. (0.5 pt)
* Perform pandas dataframe operations to answer your chosen question #2. (0.5 pt)
* Include a comment or text box with a description of the answers to your chosen questions. (0.5 pt)

In the event that you have a borderline grade (just below a grade threshold) at the end of the quarter, extra credit points may be considered when bumping students up a grade.

In [ ]:
# Run this cell to download the pokemon.csv file
!rm -f pokemon.csv
!wget -q https://dl.dropboxusercontent.com/scl/fi/kathb0yft8k573eiqtvra/pokemon.csv?rlkey=vtswtovmyql525clxklbdkmes&st=sriioni3&dl=0
!mv pokemon.csv?rlkey=vtswtovmyql525clxklbdkmes pokemon.csv

## Submission

Before you submit your notebook, ensure that you've run all the cells sequentially to display images, graphs, and outputs correctly. Take the time to review your solutions and evaluate using the public test cases. Once you're satisfied, save your notebook by navigating to "File" in the Colab Notebook menu and selecting "Save" or using the keyboard shortcut (usually Ctrl + S or Cmd + S).

To submit, export your notebook as a PDF. You can do this by going to File > Print. Then set Destination to Save as PDF. Remember to submit the correct version. Ensure this contains all your cellls, as this method sometimes cuts off part of the notebook!

Alternatively, you can download your notebook as an .ipynb file and open the notebook locally in Jupyter Notebook or JupyterLab, which you installed during week 1: https://docs.google.com/document/d/1GvmuibsigCywMGdYhdoQpFiGOKGgps3ajcaF-0I6FjY/edit?usp=sharing. You can then go to File > Save and Export Notebook as, and save your notebook as a PDF. If you run into an error trying this, you can save the notebook as an HTML file, and then save this HTML file as a PDF.

Please save your work before exporting it, and if you encounter any technical issues or have questions about the submission process, reach out to the course staff for assistance.